BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evb_rock3a"
BBFILE_PATTERN_evb_rock3a = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_evb_rock3a = "1"

LAYERSERIES_COMPAT_evb_rock3a = "whinlatter walnascar"
