BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "evb_raspberry5b"
BBFILE_PATTERN_evb_raspberry5b = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_evb_raspberry5b = "1"

LAYERSERIES_COMPAT_evb_raspberry5b = "whinlatter walnascar"
