# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "evb-rockchip"
BBFILE_PATTERN_evb-rockchip = ""
BBFILE_PATTERN_IGNORE_EMPTY_evb-rockchip = "1"
LAYERSERIES_COMPAT_evb-rockchip = "whinlatter walnascar"
