#@TYPE: Machine
#@NAME: EVB Rock3A (64bit)
#@DESCRIPTION: OpenBMC EVB machine configuration for Radxa Rock3A in 64-bit mode

MACHINEOVERRIDES =. "rock3a:rk3568:"

require conf/machine/rockchip-rk3568-evb.conf

# Use OpenBMC MMC image/profile for SD card or eMMC boot media.
require conf/distro/include/phosphor-mmc.inc

# Rock3A device tree on RK3568.
KERNEL_DEVICETREE = "rockchip/rk3568-rock-3a.dtb"

include conf/machine/include/obmc-evb-common.inc
