BBPATH .= ":${LAYERDIR}"

BBFILE_COLLECTIONS += "evb_raspberrypi"
BBFILE_PATTERN_evb_raspberrypi = "^${LAYERDIR}/"
BBFILE_PATTERN_IGNORE_EMPTY_evb_raspberrypi = "1"

LAYERSERIES_COMPAT_evb_raspberrypi = "whinlatter walnascar"
